#!/bin/sh
#----------------------------------------
# Author: Lorenzo Alluminio
# conveniency wrapper for rate.sx
# TODO:
# - improve options description
# - maybe add some checks
#----------------------------------------

usage() { 
	echo "Usage: $(basename "$0") [-n n] [-t c] [-c c] [-b begin] [-e end] [currency] [amount currency]" 1>&2
	echo "conveniency wrapper for rate.sx" 1>&2
	echo "-h, shows this help." 1>&2
	echo "-n, shows top n coins (default=10)." 1>&2
	echo "-t, convert to currency (default=base currency)" 1>&2
	echo "-c, set base currency (default=usd)." 1>&2
	echo "-b, beginning time of graph (default=30d)." 1>&2
	echo "-e, end time of graph (default=now)." 1>&2
}

TOP=10
BASE_CURRENCY="usd"
BEGIN="30d"
END="now"
while getopts ":hn:t:c:b:e:" o; do
	case "${o}" in
		n)
			TOP="${OPTARG}"
			;;
		t)
			TO="${OPTARG}"
			;;
		c)
			BASE_CURRENCY="${OPTARG}"
			;;
		b)
			BEGIN="${OPTARG}"
			;;
		e)
			END="${OPTARG}"
			;;
		h)
			usage
			exit 0
			;;
		*)
			usage
			exit 1
			;;
	esac
done
shift $((OPTIND-1))

if [ -z "$TO" ]; then
	TO="$BASE_CURRENCY"
fi

OPTIONS="F"

# if no arguments, show ranking
if [ $# -eq 0 ]; then
	OPTIONS="${OPTIONS}&n=${TOP}"
	curl -s "${TO}.rate.sx/?${OPTIONS}" | tail -n +7 
	exit 0
fi

# if one argument, show graph for coin
if [ $# -eq 1 ]; then
	COIN="$1"
	QUERY="${COIN}@${BEGIN}..${END}"
	curl -s "${TO}.rate.sx/${QUERY}?${OPTIONS}" | head -n -2
	exit 0
fi

# if 2 arguments, conversion
if [ $# -eq 2 ]; then
	AMOUNT="$1"
	FROM="$2"
	QUERY="${AMOUNT}${FROM}"
	curl -s "${TO}.rate.sx/${QUERY}?${OPTIONS}" | tr "\n" " "
	echo "$TO"
	exit 0
fi
